spring:
  #  mysql configuration
  datasource:
    url: jdbc:postgresql://containers-us-west-154.railway.app:6011/railway
    username: postgres
    password: keZY5mX9h3S5MLNUuCV7

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#mysql://root:LdKCqiJA09wIa9cRvGjk@containers-us-west-200.railway.app:7681/railway
#postgresql://postgres:keZY5mX9h3S5MLNUuCV7@containers-us-west-154.railway.app:6011/railway