server:
  port: 8080
  servlet:
    context-path: /employeeservice

spring:
  #  mysql configuration
  datasource:
    url: jdbc:postgresql://dpg-cirrabh5rnujejsuk30g-a/postgres_db1
    username: ocean
    password: NpyAPzcnf7mOUGzVcD1g1d82OQtqPxCN

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#mysql://root:LdKCqiJA09wIa9cRvGjk@containers-us-west-200.railway.app:7681/railway
#RAILWAY URL - postgresql://postgres:keZY5mX9h3S5MLNUuCV7@containers-us-west-154.railway.app:6011/railway
#RENDER URL - jdbc:postgresql://dpg-cirrabh5rnujejsuk30g-a.singapore-postgres.render.com:5432/postgres_db1